last_build_profile = "gnat_native=DEVELOPMENT,jpeglib=DEVELOPMENT"
[toolchain]
assistant = false
[toolchain.external]
gnat = false
gprbuild = false
[toolchain.use]
gnat = "gnat_native=15.2.1"
gprbuild = "gprbuild=25.0.1"

